const topicData = [
  {
    topic: "Biology",
    subtopic: [
      "Agricultural Science",
      "Biochemistry",
      "Biomarkers",
      "Biophysics",
      "Biotechbology",
      "Cell Biology",
      "Chemical Biology",
      "Developmental Biology",
      "Ecology",
      "Environmental Science",
      "Evolutionary Biology",
      "Freshwater Biology",
      "Genetics",
      "Human Biology",
      "Marine Biology",
      "MicroBiology",
      "Model organisms",
      "Moeluclar Biology",
      "Plant Biology",
      "Structural Biology",
      "Synthetic Biology",
      "Systems Biology",
      "Virology",
      "Zoology",
    ],
  },
  {
    topic: "Biomedical Science",
    subtopic: [
      "Anatomy",
      "Immunology",
      "Laboratory animal science",
      "Medicines research and development",
      "Neurobiology",
      "Nutritional science",
      "Parasitology",
      "Pharmacology",
      "Regenerative medicine",
      "Sample collections",
    ],
  },
  {
    topic: "Chemistry",
    subtopic: [
      "Analytica Chemistry",
      "Biochemistry",
      "Computational Chemistry",
      "Drug discovery",
      "Synthetic Chemistry",
    ],
  },
  {
    topic: "Computational biology",
    subtopic: [
      "Biomolecular simulations",
      "Functions analysis",
      "Molecular genetics",
      "Molecular interactions, pathways and networks",
      "Nucleic acids",
      "Phylogeny",
      "Proteins",
      "Sequence analysis",
      "Sequence sites, features and motifs",
      "Structure analysis",
    ],
  },
  {
    topic: "Computer Science",
    subtopic: [
      "Computational chemistry",
      "Data mining",
      "Data visualisations",
      "Machine learning",
      "Natural language processing",
      "Software engineering",
    ],
  },
  {
    topic: "Experimental design and studies",
    subtopic: [
      "Animal Study",
      "GWAS study",
      "Preclinical and clinical studies",
    ],
  },
  {
    topic: "Informatics",
    subtopic: [
      "Bioinformatics",
      "Biological databases",
      "Cheminformatics",
      "Laboratory information management",
      "Medical informatics",
      "Ontology and terminology",
    ],
  },
  {
    topic: "Laboratory Techniques",
    subtopic: [
      "Chromosome and conformation capture",
      "Cytometry",
      "Genotyping experiment",
      "Imaging",
      "Immunoprecipitation experiment",
      "Microarray experiment",
      "PCR experiment",
      "Protein interaction experiment",
      "Proteomics experiment",
      "RNAi experiment",
      "Sequencing",
      "Simulation experiment",
    ],
  },
  {
    topic: "Literature and language",
    subtopic: ["Natural language processing"],
  },
  {
    topic: "Mathematics",
    subtopic: [
      "Applied mathematics",
      "Pure mathematics",
      "Statistics and probability",
    ],
  },
  {
    topic: "Medicine",
    subtopic: [
      "Allergy, clinical immunology and immunotherapeutrics",
      "Anaesthesiology",
      "Cardiology",
      "Complementary medicine",
      "Dentistry",
      "Dermatology",
      "Ear, noise and throat medicine",
      "Endocrinology and metabolism",
      "Gastroenterology",
      "Gender medicine",
      "Gynaecology and obsterics",
      "Haematology",
      "Hepatic and biliary medicine",
      "Medical toxicology",
      "Musculoskeletal medicine",
      "Neurology",
      "Oncology",
      "Opthalmology",
      "Paediactrics",
      "Pain medicine",
      "Pathology",
      "Psychiatry",
      "Public health and epidemiology",
      "Reproductive health",
      "Respiratory medicine",
      "Toxicology",
      "Transational medicine",
      "Trauma medicine",
      "Urology and nephrology",
      "Veterinary medicine",
    ],
  },
  {
    topic: "Omics",
    subtopic: [
      "Fluxomics",
      "Genomics",
      "Immunomics",
      "Metabolomics",
      "Molecular evolution",
      "Phenomics",
      "Proteomics",
    ],
  },
  {
    topic: "Physics",
    subtopic: ["Biophysics"],
  },
];

export default topicData;
